from building import *

cwd  = GetCurrentDir()
src = ['USBSerial.cpp']
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['RT_USING_ARDUINO', 'ARDUINO_USING_USBSERIAL'], CPPPATH = inc)

Return('group')
