from building import *

cwd  = GetCurrentDir()
src = Glob('*.cpp')
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['RT_USING_ARDUINO', 'ARDUINO_USING_ADAFRUIT'], CPPPATH = inc)

Return('group')
