from building import *

cwd  = GetCurrentDir()
src = ['Servo.cpp']
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['RT_USING_ARDUINO', 'ARDUINO_USING_SERVO'], CPPPATH = inc)

Return('group')
