from building import *

cwd  = GetCurrentDir()
src = ['Servo.cpp']
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['PKG_USING_RTDUINO', 'RTDUINO_USING_SERVO'], CPPPATH = inc)

Return('group')
