from building import *

cwd  = GetCurrentDir()
src = ['SPI.cpp']
inc = [cwd]

group = DefineGroup('RTduino-libraries-buildin', src, depend = ['PKG_USING_RTDUINO', 'RTDUINO_USING_SPI'], CPPPATH = inc)

Return('group')
