from building import *

cwd  = GetCurrentDir()
src = ['SPI.cpp']
inc = [cwd]

#  'RTDUINO_USING_SPI'
group = DefineGroup('Arduino', src, depend = ['PKG_USING_RTDUINO'], CPPPATH = inc)

Return('group')
