from building import *

cwd  = GetCurrentDir()
src = ['Wire.cpp']
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['PKG_USING_RTDUINO', 'RTDUINO_USING_WIRE'], CPPPATH = inc)

Return('group')
