name: Arduino Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    if: github.repository_owner == 'RTduino'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
